on:
  push:
    branches:
      - slack

name: 🚀 Deploy website on push
jobs:
  ftpdeploy:
    name: ⤵️ AutoDeploy
    runs-on: ubuntu-latest

    steps:
    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      with:
        ref: slack

    - name: 🔨 Install dependencies
      run: |
        cd projects/
        pip install -r requirements.txt

    - name: 🎉 FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.dauden.cloud
        port: 21
        protocol: ftp
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: pyapp/slack/
        local-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
